# -*- coding: utf-8 -*-
"""exam11_classification_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxROBg0Tj1GCyCmPQzpuQKh0dEkIGwpX
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from keras.utils import to_categorical
from tensorflow.keras import datasets

(X_train, Y_train),(X_test, Y_test)=datasets.mnist.load_data() # MNIST 데이터셋 불러오기
print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

my_sample=np.random.randint(60000)
plt.imshow(X_train[my_sample], cmap='gray')
plt.show()
print(Y_train[my_sample])
print(X_train[my_sample])

y_train=to_categorical(Y_train)
y_test=to_categorical(Y_test)
print(Y_train[5000])
print(y_train[5000])

x_train=X_train.reshape(-1, 28*28)
x_test=X_test.reshape(-1,28*28)
x_train=x_train/255
x_test=x_test/255
print(x_train.shape)